[package]
name = "graph-algorithms"
version = "0.1.0"
edition = "2021"

[lib]
name = "graph_algorithms"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.3.1"
